### ISSUE TITLE
Telethon proxy

### ISSUE THREAD

**Issue by rnyPlanet** [exzhawk/mcp-query-a#17]
forgive me for writing here. if you developed proxy for telethon then we need help, really need it ...
noticed that you were noted in the telethon changelog that you implemented a proxy https://docs.telethon.dev/en/latest/misc/changelog.html#bot-login-and-proxy-support-v0-8
many people write that I can not connect to telegram via proxy (

**Comment by exzhawk** [comment]
You can just mention(at) me under the related issue in Telethon repo to get me involved rather than open this one.

**Comment by rnyPlanet** [comment]
> You can just mention(at) me under the related issue in Telethon repo to get me involved rather than open this one.

Thanks I'll know. I'm new
